/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ajapnhikmyjrenzsdsiu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYXBuaGlrbXlqcmVuenNkc2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MTczNzAsImV4cCI6MjA4NjQ5MzM3MH0.fBrHOBoCNLIcJsGANyx3PA9edFU6y-sjuH1-054gsM0"